//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SinglePage1.Models.DomainModels.DTO.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int? Id { get; set; }
        public Nullable<int> Code { get; set; }
        public string Title { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> Countity { get; set; }
    }
}
